Logic for Add avatar and comment
Team2DemoApp/MusicAppRepository pull request #10
Opened 2024-02-19 06:58 UTC by praveenkumartam2974

Code Logic for Add avatar and comment

2024-02-19 07:06 UTC, Dineshks15 commented on MusicAppService/controllers/userController.js
> +        Message: "No Users"
Hi @praveenkumartam2974 , Please change status code 200 -> 401

2024-02-19 07:06 UTC, Dineshks15 commented on MusicAppService/controllers/userController.js
> +        Message: "No Users"
Hi @praveenkumartam2974  , Please change status code 200 -> 401.

2024-02-20 06:32 UTC, Team2DemoApp requested changes

2024-02-20 06:32 UTC, Team2DemoApp commented on MusicAppService/services/service.js
> +async function addComment(email, comment) {
controller is sending parameters _id, comment. Why service has email? From where this email will be set?
**const userComment = await UserService.addComment(
      _id,
      comment
    );**

2024-02-20 06:32 UTC, Team2DemoApp commented on MusicAppService/services/service.js
> +    });
what is the use of this playlist?

2024-02-20 06:32 UTC, Team2DemoApp commented on MusicAppService/services/service.js
> +    );
comment is in playlist schema, why find is done from users?

And, where is add happening?

2024-02-20 11:23 UTC, closed without merging

2024-02-20 11:23 UTC, Team2DemoApp commented
@praveenkumartam2974, PR cannot be merged, comments addressed in another PR.